#!/bin/bash

function COMPILE {
$ROOTSYS/bin/root -n -b -q  compile.C  >/dev/null
}



i=0
while [ "$1" != "" ]; do
  echo "parameter $i:  $1"
  i=$(( $i + 1 ))
  shift
done	
####################################



echo "$1" | grep "\-I" > /dev/null
if [ "$?" = "0" ]; then
    echo ... INCLUDE ... compiling
    COMPILE
    exit
fi 

echo "$1" | grep "CMakeFiles/" | grep ".C.o" >/dev/null
if [ "$?" = "0" ]; then
    echo ... CMake ... linking
    ls -l *.so
    paths=`cat ~/.rootrc | grep -v -e "^\#" | grep Unix | grep DynamicPath | awk '{print $2}'`
#    echo POSSIBLE DESTINATION: $paths
    IFS=':' read -ra ADDR <<< "$paths"
    for i in "${ADDR[@]}"; do
	ii=` sed   "s#~#$HOME#" <<< $i`
	i="$ii"
	echo "PATH:    " "$i"
	if [ "$i" != "." ]; then
	    if [ -d "$i" ]; then
		echo "      ..  directory $i exists, i copy here"
		cp *.so $i/
		break
	    fi
	fi
    done
    exit
fi 

   
