#!/bin/bash

DEBUG=0
if [ "$1" = "debug" ]; then
    DEBUG=1
else
    DEBUG=0
fi

#credentials...........
CREDFILE="shspe.pk_mysql"

function runnumber {
    local RF=$1
    echo $RF | grep "^run" >/dev/null
    if [ "$?" != "0" ]; then
	echo not a run
	exit
    fi
    # run reomve; nonnumbers to =; first field; remove leading 0
    echo $RF | sed  "s/^run//g" | sed  "s/[^0-9]/=/g" | cut -d = -f 1 | sed  "s/^0\+//g"
#    echo $RF2
}


##################################### BEGIN ########
##################################### BEGIN ########
##################################### BEGIN ########
##################################### BEGIN ########

if [ ! -e $CREDFILE ]; then
#else
#  exit  
    if [ "$DEBUG" = "1" ]; then
	#echo $CREDFILE exists;
	echo you need file $CREDFILE:
	echo user=
	echo pass=
	echo database=
    fi
  exit
fi

 if [ "$DEBUG" = "1" ]; then echo ... going to parse $CREDFILE; fi
USER=`cat $CREDFILE | grep -v \# | grep user= | cut -d = -f 2`
 if [ "$DEBUG" = "1" ]; then echo USER=$USER; fi
PASS=`cat $CREDFILE | grep -v \# | grep pass= | cut -d = -f 2`
DBASE=`cat $CREDFILE | grep -v \# | grep database= | cut -d = -f 2`
if [ "$DBASE" = "" ]; then
     if [ "$DEBUG" = "1" ]; then echo ... no DBASE name defined;fi
    exit
fi
#echo DBASE=$DBASE
# i need
#    user,pass,server,databasename,run number
########################################################


#runnumber run0048_20140628_095336.root
#RUN=`runnumber run0048_20140628_095336.root`
RUNNAME=`cat .CURRENTFILE`
if [ "$DEBUG" = "1" ]; then echo "d ... runname $RUNNAME"; fi
RUNBA=`basename $RUNNAME`
if [ "$DEBUG" = "1" ]; then echo "d ... runfull $RUNBA"; fi
RUN=`runnumber $RUNBA`
if [ "$DEBUG" = "1" ]; then echo "d ... run     $RUN"; fi
RUN=$(( $RUN + 0 ))
if [ "$DEBUG" = "1" ]; then echo "d ... run     $RUN"; fi

if [ "$RUN" -ge "0" -a "$RUN" -le "9999" ]; then
    echo ======== bash script for insert to mysql=======
else
    exit
fi
echo "i ... run /$RUN/; database /$DBASE"
#echo "# run /$RUN/ saved to database $DBASE " >> zfitresults.eff

### LAST FIT SAVED RESULT:
### zfitresults.tmp###########################3
#k dk A dA cc:scom histoname=cut=d=diag=
#
#  naming from mkmat
#     c022=>diag6 ...22-16 = de6 = #6
#         =>cutd t6d 
#HOW?
pkid=0
while read line           
do
    #ALL depends ok order
    # k dk A dA  5from 6to 7code 8name file
    if [ "$DEBUG" = "1" ]; then echo i ... database /$DBASE/; fi
    echo -e "$line"
    pkid=$(( $pkid + 1 ))
    part='n'
     k=`echo $line | awk '{print $1}'`
    dk=`echo $line | awk '{print $2}'`
     A=`echo $line | awk '{print $3}'`
    dA=`echo $line | awk '{print $4}'`
    fitcode=`echo $line | awk '{print $7}'`
    #### histoname $6   c022  t3_d    t4_diag    #8
    detnumbr=0
    det=`echo $line | awk '{print $8}'`
    ###########  first ... check c0024 ###############
    echo $det | grep -e "^c" >/dev/null
    if [ "$?" = "0" ]; then
	detnumbr=`echo $det | sed 's/c//' | awk '{print $1-16}'`
    else
    ######################################  c017 ... c022
      if [ "$DEBUG" = "1" ]; then echo i ... detector /$det/... not c022; fi
      detnum=`echo $det | awk 'BEGIN{FS="_"} {print substr($1,2,1);}'`
      detlet=`echo $det | awk 'BEGIN{FS="_"} {print substr($1,1,1);}'`
      if [ "$DEBUG" = "1" ]; then echo i ... letter=t  /$detlet/; fi
      if [ "$DEBUG" = "1" ]; then echo i ... detnumbr /$detnum/; fi
      part=`echo $det | awk 'BEGIN{FS="_"} {print $2}'`
      if [ "$DEBUG" = "1" ]; then echo i ... particle /$part/; fi
    fi
    #####################################
    valid=1
    sig=1.
    dsig=0.1
    run=$RUN
    
    echo "INSERT INTO  peaks (pkid,run, det,part,t,k,dk,A,dA,sig,dsig,fitcode,valid) VALUES ('$pkid','$run', '$detnum','$part',NOW(),'$k','$dk','$A','$dA','$sig','$dsig','$fitcode','$valid');" | mysql -u$USER -p$PASS $DBASE 2>/dev/null;
    echo "r ... result $?"
    
done <zfitresults.tmp



exit
############################################################    EXIT
########################################################    EXIT
####################################################    EXIT
################################################    EXIT

pkid=1
run=$RUN
#HOW?  c019
det=2
#HOW?  contour
part='d'
k=$1
dk=$2
A=$3
dA=$4
sig=1.
dsig=0.1

fitcode="ccc+p1:scom"
fitcode="$5"
valid=1
echo "INSERT INTO  peaks (pkid,run, det,part,t,k,dk,A,dA,sig,dsig,fitcode,valid) VALUES ('$pkid','$run', '$det','$part',NOW(),'$k','$dk','$A','$dA','$sig','$dsig','$fitcode','$valid');" | mysql -u$USER -p$PASS $DBASE   2>/dev/null ;

