#!/bin/bash

MACDIR=$HOME/root_macros

mkdir -p  $MACDIR

if [ -e $MACDIR ]; then
 echo ok, MACRO DIR $MACDIR exists .. i probably created
else
    MACDIR=$HOME/00_central
    if [ -e $MACDIR ]; then
	echo ok,  MACRO DIR $MACDIR exists
    else
	echo NEITHER $HOME/root_macros NOR $HOME/00_central FOUND 
	echo create first MACRO DIRECTORY ...
	exit 1
    fi
fi




echo This installs .rootrc and .rootlogon scripts
echo ...
A=""
B=""
y="y"

if [ -e $HOME/.rootrc ]; then
A="$HOME/.rootrc"
fi

if [ -e $HOME/.rootlogon ]; then
B="$HOME/.rootlogon"
fi

if [[  -e $HOME/.rootrc && -e $HOME/.rootlogon ]]; then
 echo Warning: the scripts ~/.rootrc and ~/.rootlogon already EXIST
 echo -n Do you want to overwrite? \(y/n\)
 read  y 
else

if [[  -e $HOME/.rootrc || -e $HOME/.rootlogon ]]; then
 echo Warning: the script $A $B already EXISTS
 echo -n Do you want to overwrite? \(y/n\)
 read  y 
fi
fi

DT=`date +%Y%m%d_%H%M%S`
 
if [ "$y" = "y" ]; then
 echo ... making backup
 tar -cvzf $HOME/.rootrclogon_backup_$DT.tgz $HOME/.rootrc $HOME/.rootlogon 2>/dev/null
 ls -ltr $HOME/.rootrclogon_backup_$DT.tgz
 echo ...
 cp rootrc  $HOME/.rootrc
 cp rootlogon $HOME/.rootlogon
 ls -ltrh $HOME/.rootrc $HOME/.rootlogon
 echo SCRIPTS COPPIED...backup created
else
 echo ok....quitting
fi


